In [53]:
# pacotes
# nao esquecer!! instalar o ipykernel uv add --dev ipykernel
import polars as pl

## Amazon

In [54]:
# getting data
amazon = pl.read_csv("../data/raw/Amazon.csv", encoding="latin1")

In [57]:
# dando uma olhada
amazon.glimpse()

Rows: 1363
Columns: 5
$ id           <str> 'b000jz4hqo', 'b0006zf55o', 'b00004tkvy', 'b000g80lqo', 'b0006se5bq', 'b000ehpzv8', 'b00021xhzw', 'b000gzwjgc', 'b0000dbykm', 'b00029bqa2'
$ title        <str> 'clickart 950 000 - premier image pack (dvd-rom)', 'ca international - arcserve lap/desktop oem 30pk', "noah's ark activity center (jewel case ages 3-8)", 'peachtree by sage premium accounting for nonprofits 2007', 'singing coach unlimited', 'emc retrospect 7.5 disk to disk windows', 'adobe after effects professional 6.5 upgrade from standard to professional', 'acad upgrade dragon naturallyspeaking pro solution 9.0 (a289a-fd7-9.0)', "mia's math adventure: just in time", "disney's 1st & 2nd grade bundle (pixar 1st grade secret keys and aladdin reading quest)"
$ description  <str> null, 'oem arcserve backup v11.1 win 30u for laptops and desktops', null, "peachtree premium accounting for nonprofits 2007 is the affordable easy to use accounting solution that provides you with donor/grantor management. if you're like most nonprofit organizations you're constantly striving to maximize each and every dollar of your annual operating budget. financial reporting by programs and funds advanced operational reporting and the rock-solid core accounting features that have made peachtree the choice of hundreds of thousands of small businesses. the result is an accounting solution tailor-made for the challenges of operating a nonprofit organization. keep an audit trail to record and report on any changes made to your transactions improve data integrity with prior period locking archive your organization's data for snap shots of your data before you closed your year set up individual user profiles with password protection peachtree restore wizard restores all backed-up data files plus web transactions and customized forms includes all standard accounting features - general ledger accounts receivable &accounts payable; payroll solutions; time & billing and job costing; fixed assets; analysis and reporting & customization easily convert from quickbooks", 'singing coach unlimited - electronic learning products (win me nt 2000 xp)', 'emc retrospect 7.5 disk to diskcromwindows', 'upgrade only; installation of after effects standard new disk caching tools speed up your interactive work save any combination of animation parameters as presets -- create transformations masks expressions effects and text tighter integration with other adobe tools - import photoshop cs and illustrator cs files with preserved layers and other attributes output to firewire for easier previewing on ntsc and pal video monitors', '- marketing information: dragon naturallyspeakingprofessional 9 will saveyou and your organizationmoney because itempowers anyone tocreate documents overthree times faster thantyping. it also protectsagainst repetitive stressinjuries that result in lostproductivity higher workers compensationpremiums and higher temporary labor costs.the accuracy performance and ease-of-use indragon naturallyspeaking professional 9make it the ideal solution for busy corporateprofessionals. you and your employees canuse dragon naturallyspeaking professionalto create documents and email messages write reports and complete forms all by voice. product information - software sub type: voice recognition - software name: dragon naturallyspeaking v.9.0 professional - upgrade - features and benefits: - the most accurate ever - faster and safer than typing - section 508 certified - easy to use - no special user training required - support for citrix thin-client environments - enterprise ready - ease of administration - mobility - bluetooth support - robust customization - natural language capabilities - text to speech - language support: english - platform support: pc miscellaneous - compatibility: - microsoft office applications: word excel outlook andpowerpoint - corel wordperfect', "in mia's math adventure: just in time children will help mia save her house by using their math skills!", "disney's 1st & 2nd grade bundle will help your child learn while challenging their imagination. skill-building activities will develop a love of education in your child. features disney/pixar buzz lightyear learning 1st grade aladdin reading quest and disney's search for the secret keys."
$ manufacturer <str> 'broderbund', 'computer associates', 'victory multimedia', 'sage software', 'carry-a-tune technologies', 'dantz', 'adobe', 'nuance academic', 'kutoka', 'disney'
$ price        <f64> 0.0, 0.0, 0.0, 599.99, 99.99, 0.0, 499.99, 399.54, 19.99, 14.99

colunas: 
id: codigo identificador da linha
title: titulo do anuncio
description: descricao do anuncio 
manufacturer: fabricante
price: preço em usd

In [58]:
amazon.schema                         # nomes e tipos das colunas (≈ str())

Schema([('id', String),
        ('title', String),
        ('description', String),
        ('manufacturer', String),
        ('price', Float64)])

In [59]:

amazon.null_count()                   # NAs por coluna (≈ colSums(is.na(df)))

shape: (1, 5)
┌─────┬───────┬─────────────┬──────────────┬───────┐
│ id  ┆ title ┆ description ┆ manufacturer ┆ price │
│ --- ┆ ---   ┆ ---         ┆ ---          ┆ ---   │
│ u32 ┆ u32   ┆ u32         ┆ u32          ┆ u32   │
╞═════╪═══════╪═════════════╪══════════════╪═══════╡
│ 0   ┆ 0     ┆ 115         ┆ 0            ┆ 0     │
└─────┴───────┴─────────────┴──────────────┴───────┘

In [60]:
amazon["manufacturer"].value_counts(sort=True)   # ≈ count(df, manufacturer, sort = TRUE)

shape: (350, 2)
┌─────────────────────────────┬───────┐
│ manufacturer                ┆ count │
│ ---                         ┆ ---   │
│ str                         ┆ u32   │
╞═════════════════════════════╪═══════╡
│ adobe                       ┆ 87    │
│ encore software             ┆ 76    │
│ topics entertainment        ┆ 73    │
│ encore                      ┆ 62    │
│ microsoft                   ┆ 58    │
│ …                           ┆ …     │
│ midisoft corporation        ┆ 1     │
│ true north technology inc.  ┆ 1     │
│ language engineering co llc ┆ 1     │
│ topics education            ┆ 1     │
│ alfred publishing           ┆ 1     │
└─────────────────────────────┴───────┘

In [61]:
amazon["manufacturer"].n_unique()     # ≈ n_distinct()

350

## Google

In [62]:
import sys
sys.executable

'C:\\Users\\estatistica\\AppData\\Local\\Programs\\Python\\Python314\\python.exe'

In [ ]:
google = pl.read_csv(
    "../data/raw/GoogleProducts.csv",
    encoding="latin1",
    schema_overrides={"price": pl.String},
)
google.glimpse()

# tem que ler price como string pq ta dando erro

Rows: 3226
Columns: 5
$ id           <str> 'http://www.google.com/base/feeds/snippets/11125907881740407428', 'http://www.google.com/base/feeds/snippets/11538923464407758599', 'http://www.google.com/base/feeds/snippets/11343515411965421256', 'http://www.google.com/base/feeds/snippets/12049235575237146821', 'http://www.google.com/base/feeds/snippets/12244614697089679523', 'http://www.google.com/base/feeds/snippets/12311932123270766595', 'http://www.google.com/base/feeds/snippets/13364214809208487698', 'http://www.google.com/base/feeds/snippets/12835181529749808477', 'http://www.google.com/base/feeds/snippets/12949835105262366018', 'http://www.google.com/base/feeds/snippets/12991998923940483779'
$ name         <str> 'learning quickbooks 2007', 'superstart! fun with reading & writing!', 'qb pos 6.0 basic software', 'math missions: the amazing arcade adventure (grades 3-5)', 'production prem cs3 mac upgrad', 'video studio 11 plus', 'edius pro 4', 'qb pos 6.0 pro multi store sw', 'qb credit card kit 3.0', 'vegas movie studiodvd+8 plat'
$ description  <str> 'learning quickbooks 2007', 'fun with reading & writing! is designed to help kids learn to read and write better through exercises puzzle-solving creative writing decoding and more!', 'qb pos 6.0 basic retail mngmt software. for retailers who need basic inventory sales and customer tracking.', "save spectacle city by disrupting randall underling's plan to drive all the stores out of business and take over the city. solve real-world math challenges in the uniquely entertaining stores and make theme successful again.", 'adobe cs3 production premium mac upgrade from production studio premium or standard', 'corel video studio 11 plus is consumer video editing and dvd authoring software that lets anyone do more with video.', 'whether you are working with standard definition or high definition video grass valley edius pro nle software frees you from the limitations of conventional editing systems. edius pro software can be upgraded to edius broadcast at any time.', 'qb pos 6.0 pro multistore retail mngmt software. has all the features in basic plus the ability to manage up to ten stores from a single office.', 'quickbooks credit card kit v3.0 (2007)', 'sony media software vegas movie studio +dvd 8 platinum edition. video editing and dvd creation software vegas movie studio platinum edition software provides the power features and advanced tools you need to edit video in nearly any format ...'
$ manufacturer <str> 'intuit', null, 'intuit', null, 'adobe software', 'corel corporation', 'canopus/grass valley', 'intuit', 'intuit', 'sony creative software'
$ price        <str> '38.99', '8.49', '637.99', '12.95', '805.99', '103.99', '585.99', '1054.99', '25.99', '92.99'

In [67]:
google.schema

Schema([('id', String),
        ('name', String),
        ('description', String),
        ('manufacturer', String),
        ('price', String)])

In [68]:
amazon.null_count()                   # NAs por coluna (≈ colSums(is.na(df)))

shape: (1, 5)
┌─────┬───────┬─────────────┬──────────────┬───────┐
│ id  ┆ title ┆ description ┆ manufacturer ┆ price │
│ --- ┆ ---   ┆ ---         ┆ ---          ┆ ---   │
│ u32 ┆ u32   ┆ u32         ┆ u32          ┆ u32   │
╞═════╪═══════╪═════════════╪══════════════╪═══════╡
│ 0   ┆ 0     ┆ 115         ┆ 0            ┆ 0     │
└─────┴───────┴─────────────┴──────────────┴───────┘

In [69]:
amazon["manufacturer"].n_unique()     # ≈ n_distinct()

350